
services:
  - type: web
    name: terra-xmd
    env: node
    plan: free
    repo: https://github.com/PrinceXtremeX/XTREME-XMD.git
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MODE
        value: private
      - key: PREFIX
        value: ✨
      - key: BOT_NAME
        value: XTREME-XMD
      - key: OWNER_NUMBER
        value: 237695429381
